In [1]:
import pandas as pd
import numpy as np
import logging
import re

In [2]:
import os
import logging

# Create logs folder if not exists
os.makedirs('../logs', exist_ok=True)

logging.basicConfig(
    filename='../logs/pipeline.log',
    level=logging.ERROR,
    format='%(asctime)s:%(levelname)s:%(message)s'
)

print("Logging Configured Successfully")

Logging Configured Successfully

In [3]:
customers = pd.read_csv('../data/customers.csv')
campaigns = pd.read_csv('../data/campaigns.csv')

print("Customers Data")
display(customers)

print("Campaigns Data")
display(campaigns)

Customers Data

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

Campaigns Data

,OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email_address
0,1,Medium,4,3,1,33.73,NaN,NaN
1,1,Medium,4,3,2,35.67,NaN,NaN
2,1,Medium,4,3,3,29.03,NaN,NaN
3,1,Medium,4,3,4,39.25,NaN,NaN
4,2,Medium,5,2,1,27.81,NaN,NaN
...,...,...,...,...,...,...,...,...
543,919,Large,2,1,4,64.34,NaN,NaN
544,920,Large,14,2,1,50.20,NaN,NaN
545,920,Large,14,2,2,45.75,NaN,NaN
546,920,Large,14,2,3,44.29,NaN,NaN
547,920,Large,14,2,4,49.41,NaN,NaN

In [4]:
print(customers.info())

print(campaigns.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548 entries, 0 to 547
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OutletID          548 non-null    int64
 1   MarketSize        548 non-null    object
 2   AgeofOutlets      548 non-null    int64
 3   Campaigns         548 non-null    int64
 4   Week              548 non-null    int64
 5   SalesInThousands  548 non-null    float64
 6   Unnamed: 6        0 non-null      float64
 7   email_address     0 non-null      float64
dtypes: float64(3), int64(4), object(1)
memory usage: 34.4+ KB
None

In [5]:
print(combined.columns)

NameError: name 'combined' is not defined

In [6]:
campaigns = campaigns.rename(columns={
    'cust_id': 'customer_id',
    'customer_name': 'name',
    'email_address': 'email'
})

display(campaigns)

,OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email
0,1,Medium,4,3,1,33.73,NaN,NaN
1,1,Medium,4,3,2,35.67,NaN,NaN
2,1,Medium,4,3,3,29.03,NaN,NaN
3,1,Medium,4,3,4,39.25,NaN,NaN
4,2,Medium,5,2,1,27.81,NaN,NaN
...,...,...,...,...,...,...,...,...
543,919,Large,2,1,4,64.34,NaN,NaN
544,920,Large,14,2,1,50.20,NaN,NaN
545,920,Large,14,2,2,45.75,NaN,NaN
546,920,Large,14,2,3,44.29,NaN,NaN
547,920,Large,14,2,4,49.41,NaN,NaN

In [7]:
campaigns['phone'] = np.nan

display(campaigns)

,OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone
0,1,Medium,4,3,1,33.73,NaN,NaN,NaN
1,1,Medium,4,3,2,35.67,NaN,NaN,NaN
2,1,Medium,4,3,3,29.03,NaN,NaN,NaN
3,1,Medium,4,3,4,39.25,NaN,NaN,NaN
4,2,Medium,5,2,1,27.81,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
543,919,Large,2,1,4,64.34,NaN,NaN,NaN
544,920,Large,14,2,1,50.20,NaN,NaN,NaN
545,920,Large,14,2,2,45.75,NaN,NaN,NaN
546,920,Large,14,2,3,44.29,NaN,NaN,NaN
547,920,Large,14,2,4,49.41,NaN,NaN,NaN

In [8]:
combined = pd.concat([customers, campaigns], ignore_index=True)

display(combined)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone
0,1.0,Male,19.0,15.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Male,21.0,15.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Female,20.0,16.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Female,23.0,16.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Female,31.0,17.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,NaN,NaN,NaN,NaN,NaN,919.0,Large,2.0,1.0,4.0,64.34,NaN,NaN,NaN
744,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,1.0,50.20,NaN,NaN,NaN
745,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,2.0,45.75,NaN,NaN,NaN
746,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,3.0,44.29,NaN,NaN,NaN
747,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,4.0,49.41,NaN,NaN,NaN

In [9]:
combined.isnull().sum()

CustomerID                548
Gender                    548
Age                       548
Annual Income (k$)        548
Spending Score (1-100)    548
OutletID                  200
MarketSize                200
AgeofOutlets              200
Campaigns                 200
Week                      200
SalesInThousands          200
Unnamed: 6                748
email                     748
phone                     748
dtype: int64

In [10]:
combined['phone'] = combined['phone'].fillna('Not Available')

display(combined)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone
0,1.0,Male,19.0,15.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
1,2.0,Male,21.0,15.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
2,3.0,Female,20.0,16.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
3,4.0,Female,23.0,16.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
4,5.0,Female,31.0,17.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,NaN,NaN,NaN,NaN,NaN,919.0,Large,2.0,1.0,4.0,64.34,NaN,NaN,Not Available
744,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,1.0,50.20,NaN,NaN,Not Available
745,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,2.0,45.75,NaN,NaN,Not Available
746,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,3.0,44.29,NaN,NaN,Not Available
747,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,4.0,49.41,NaN,NaN,Not Available

In [11]:
combined = combined.drop_duplicates()

display(combined)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone
0,1.0,Male,19.0,15.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
1,2.0,Male,21.0,15.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
2,3.0,Female,20.0,16.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
3,4.0,Female,23.0,16.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
4,5.0,Female,31.0,17.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,NaN,NaN,NaN,NaN,NaN,919.0,Large,2.0,1.0,4.0,64.34,NaN,NaN,Not Available
744,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,1.0,50.20,NaN,NaN,Not Available
745,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,2.0,45.75,NaN,NaN,Not Available
746,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,3.0,44.29,NaN,NaN,Not Available
747,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,4.0,49.41,NaN,NaN,Not Available

In [12]:
import re

def validate_email(email):
    
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    
    if re.match(pattern, str(email)):
        return True
    else:
        return False

combined['valid_email'] = combined['email'].apply(validate_email)

display(combined)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone,valid_email
0,1.0,Male,19.0,15.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
1,2.0,Male,21.0,15.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
2,3.0,Female,20.0,16.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
3,4.0,Female,23.0,16.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
4,5.0,Female,31.0,17.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,NaN,NaN,NaN,NaN,NaN,919.0,Large,2.0,1.0,4.0,64.34,NaN,NaN,Not Available,False
744,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,1.0,50.20,NaN,NaN,Not Available,False
745,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,2.0,45.75,NaN,NaN,Not Available,False
746,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,3.0,44.29,NaN,NaN,Not Available,False
747,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,4.0,49.41,NaN,NaN,Not Available,False

In [13]:
invalid_records = combined[combined['valid_email'] == False]

display(invalid_records)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),OutletID,MarketSize,AgeofOutlets,Campaigns,Week,SalesInThousands,Unnamed: 6,email,phone,valid_email
0,1.0,Male,19.0,15.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
1,2.0,Male,21.0,15.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
2,3.0,Female,20.0,16.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
3,4.0,Female,23.0,16.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
4,5.0,Female,31.0,17.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Available,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,NaN,NaN,NaN,NaN,NaN,919.0,Large,2.0,1.0,4.0,64.34,NaN,NaN,Not Available,False
744,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,1.0,50.20,NaN,NaN,Not Available,False
745,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,2.0,45.75,NaN,NaN,Not Available,False
746,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,3.0,44.29,NaN,NaN,Not Available,False
747,NaN,NaN,NaN,NaN,NaN,920.0,Large,14.0,2.0,4.0,49.41,NaN,NaN,Not Available,False

In [14]:
invalid_records.to_csv(
    '../output/invalid_records.csv',
    index=False
)

print("Invalid Records Saved")

Invalid Records Saved

In [15]:
clean_data = combined[combined['valid_email'] == True]

clean_data.to_csv(
    '../output/clean_data.csv',
    index=False
)

print("Clean Data Saved")

Clean Data Saved

In [16]:
print("Total Records :", len(combined))

print("Valid Records :", len(clean_data))

print("Invalid Records :", len(invalid_records))

Total Records : 748
Valid Records : 0
Invalid Records : 748

In [17]:
display(clean_data)

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100), OutletID, MarketSize, AgeofOutlets, Campaigns, Week, SalesInThousands, Unnamed: 6, email, phone, valid_email]
Index: []

In [18]:
!pip install pymysql

Requirement already satisfied: pymysql in e:\python internship program\anaconda\lib\site-packages (1.2.0)

In [19]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in e:\python internship program\anaconda\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in e:\python internship program\anaconda\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\python internship program\anaconda\lib\site-packages (from sqlalchemy) (4.12.2)

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:DEV%40patel5509@localhost/pipeline_project"
)

print("Database Connected Successfully")

Database Connected Successfully

In [23]:
clean_data.to_sql(
    name='clean_customers',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data Stored Successfully")

Data Stored Successfully